[Image]
NextImage = ['Right', 'J']
PreviousImage = ['Left', 'K']
RotateLeft = ['Up', 'H']
RotateRight = ['Down', 'L']
OriginalSize = ['S']
FillWindow = ['X']
Escape = ['Escape']
Quit = ['Q']
FullScreen = ['F']

[Gallery]
Quit = ['Q']
ScrollDown = ['Down', 'J']
ScrollUp = ['Up', 'K']