[Image]
NextImage = ['Right', 'J']
PreviousImage = ['Left', 'K']
RotateLeft = ['Up', 'H']
RotateRight = ['Down', 'L']
OriginalSize = ['S']
FillWindow = ['X']
Filtering = ['B']
ShowGallery = ['Escape'] 
ShowTagbar = ['T'] 
Quit = ['Q']
FullScreen = ['F']
RunCmdA = ['E']
CmdA = 'echo "$FILE" > ~/hello.txt'
SaveImage = ['U']
SaveDir = ""

[Gallery]
Quit = ['Q', 'Escape']
ScrollDown = ['Down', 'J']
ScrollUp = ['Up', 'K']
PathLevelUp = ['BackSpace']
ToggleFilenames = ['N']

[General]
ThumbnailDir = ''
DefaultWidth = 1024.0
DefaultHeight = 1024.0
TileWidth = 300.0
TileGap = 5.0
Workers = 8
ImagesPerPage = 500